### ISSUE TITLE
Using apk version of JDK causes "java.lang.SecurityException: Can not initialize cryptographic mechanism"

### ISSUE THREAD

**Issue by lfvjimisola** [adoptium/installer#572]
We recently went from the tarball of Eclipse Temurin to apk version by @gdams. Currently, on latest (17.0.5_p8-r0).

It seems as there is something wrong with the build.

1. Is there a dependency missing?
1. I noticed that it seems as if JAVA_HOME is not set. Could that be part of the problem?
1. Also, noticed that there is quite a difference in catalog structure between our Eclipse Temurin (using SDKMAN on Ubuntu) and the alpine apk:

* Ubuntu (SDKMAN, tarball): `bin  conf  include  jmods  legal  lib  man  NOTICE  release`
* alpine apk: `bin      include  lib`

E.g. conf( /security/policy) is missing.

```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at java.base/javax.crypto.Cipher.getInstance(Cipher.java:546)
	at java.base/sun.security.ssl.SSLCipher.isTransformationAvailable(SSLCipher.java:511)
	at java.base/sun.security.ssl.SSLCipher.<init>(SSLCipher.java:500)
	at java.base/sun.security.ssl.SSLCipher.<clinit>(SSLCipher.java:82)
	at java.base/sun.security.ssl.CipherSuite.<clinit>(CipherSuite.java:65)
	at java.base/sun.security.ssl.SSLContextImpl.getApplicableSupportedCipherSuites(SSLContextImpl.java:3[43]	at java.base/sun.security.ssl.SSLContextImpl$AbstractTLSContext.<clinit>(SSLContextImpl.java:556)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:375)
	at java.base/java.security.Provider$Service.getImplClass(Provider.java:1933)
	at java.base/java.security.Provider$Service.getDefaultConstructor(Provider.java:1964)
	at java.base/java.security.Provider$Service.newInstanceOf(Provider.java:1878)
	at java.base/java.security.Provider$Service.newInstanceUtil(Provider.java:1886)
	at java.base/java.security.Provider$Service.newInstance(Provider.java:1861)
	at java.base/sun.security.jca.GetInstance.getInstance(GetInstance.java:236)
	at java.base/sun.security.jca.GetInstance.getInstance(GetInstance.java:164)
	at java.base/javax.net.ssl.SSLContext.getInstance(SSLContext.java:185)
	at java.base/javax.net.ssl.SSLContext.getDefault(SSLContext.java:110)
	at java.base/javax.net.ssl.SSLSocketFactory.getDefault(SSLSocketFactory.java:83)
	at java.base/javax.net.ssl.HttpsURLConnection.getDefaultSSLSocketFactory(HttpsURLConnection.java:336)
	at java.base/javax.net.ssl.HttpsURLConnection.<init>(HttpsURLConnection.java:292)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.<init>(HttpsURLConnectionImpl.java:81)
	at java.base/sun.net.www.protocol.https.Handler.openConnection(Handler.java:62)
	at java.base/sun.net.www.protocol.https.Handler.openConnection(Handler.java:57)
	at java.base/java.net.URL.openConnection(URL.java:1094)
	at org.apache.maven.wrapper.DefaultDownloader.downloadInternal(DefaultDownloader.java:100)
	at org.apache.maven.wrapper.DefaultDownloader.download(DefaultDownloader.java:93)
	at org.apache.maven.wrapper.Installer.createDist(Installer.java:86)
	at org.apache.maven.wrapper.WrapperExecutor.execute(WrapperExecutor.java:1[55]	at org.apache.maven.wrapper.MavenWrapperMain.main(MavenWrapperMain.java:72)
Caused by: java.lang.SecurityException: Can not initialize cryptographic mechanism
	at java.base/javax.crypto.JceSecurity.<clinit>(JceSecurity.java:119)
	... 30 more
Caused by: java.lang.SecurityException: Can't read cryptographic policy directory: unlimited
	at java.base/javax.crypto.JceSecurity.setupJurisdictionPolicies(JceSecurity.java:333)
	at java.base/javax.crypto.JceSecurity$1.run(JceSecurity.java:110)
	at java.base/javax.crypto.JceSecurity$1.run(JceSecurity.java:107)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:[56]	at java.base/javax.crypto.JceSecurity.<clinit>(JceSecurity.java:106)
	... 30 more
```

**Comment by lfvjimisola** [comment]
Issue resolved. I forgot that I asked about the different apk versions [here](https://github.com/adoptium/installer/issues/220#issuecomment-1360543372).

```
temurin-17-jdk-17.0.4.1_p1-r0
temurin-17-jdk-17.0.5_p8-r0
temurin-17-17.0.4.1_p1-r0
temurin-17-17.0.5_p8-r0
temurin-17-src-17.0.4.1_p1-r0
temurin-17-src-17.0.5_p8-r0
```
Using the non-jdk (i.e. no "-jdk") suffix) resolved the issue. Although, I've noticed that JAVA_HOME does not seem to be set. Could be that is causing us other problems. Investigating and will report back here.
